name: Run Black Formatter

on:
  pull_request:
    branches:
      - main
    paths:
      - server/app/**
      - server/main.py

jobs:
  black:
    runs-on: [ self-hosted, solinas-medium ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Black
        run: pip install black[jupyter]

      - name: Run Black
        run: black --check app main.py
