services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - app/.env.dev
    depends_on:
      db:
        condition: service_healthy # This makes it wait for the db to be ready
    networks:
      - app-network

  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pairpay
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pairpay"]
      interval: 10s # Check every 10 seconds
      timeout: 5s # Wait up to 5 seconds for a response
      retries: 5
      start_period: 10s # Give it 10s to start up before starting checks

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
